import type { OffsideIncident } from '@/types';

export const mockOffsideIncident: OffsideIncident = {
  incidentId: 'VAR-OFF-67-001',
  frameId: 194821,
  timecode: '01:07:24.482',
  camera: 'CAM-07 TACTICAL SLOW-MO',
  aiEstimation: 'ONSIDE',
  marginMeters: 0.142,
  uncertaintyMeters: 0.018,
  aiConfidence: 92.4,
  attacker: {
    jersey: 19,
    name: 'Mason Mount',
    team: 'Chelsea FC / Man City',
    bodyPartDatum: 'Upper Right Acromion (Legal)',
    axisMeters: 34.08,
    velocityKph: 31.4,
    accelerationMs2: 2.18,
    bodyLeanAngle: 18.4,
    centroid: { x: 34.08, y: -8.12, z: 1.42 },
  },
  defender: {
    jersey: 15,
    name: 'Eric Dier',
    team: 'Tottenham Hotspur',
    bodyPartDatum: 'Right Boot Cleat Heel Contact',
    axisMeters: 34.22,
    centroid: { x: 34.22, y: -7.88, z: 0.12 },
  },
  ballContact: {
    timecode: '01:07:24.482',
    frameId: 194821,
    ballSpeedKph: 94.2,
    confirmed: true,
  },
  cameraParams: {
    focal: '85mm',
    aperture: 'ƒ/2.8',
    distortion: '0.002%',
  },
  refereeStatus: 'D. ROSETTI (VAR-1)',
  broadcastStatus: '4K RAW 120FPS',
  latencyToPitchMs: 12,
};
